title: AI Developers  
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://glzbcrt.github.io/ai-developers

aux_links:
  Template Repository: https://github.com/glzbcrt/ai-developers
